[build]
  command = "npm run build"
  publish = "dist"  # Your Vite output folder

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200
  force = true  # Ensures it hits the function

[[redirects]]
  from = "/result/*"
  to = "/.netlify/functions/result/:splat"
  status = 200
  force = true