
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200
  force = true

[[redirects]]
  from = "/result/*"
  to = "/.netlify/functions/result"
  status = 200
  force = true